----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--Вычисляемое поле "Объем социальной услуги в день (мин.)"
--Добавляется к числовому значению уточнение о мимнутах.
ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN EXECUTE_TIME_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD EXECUTE_TIME_TITLE AS (CONVERT(VARCHAR, EXECUTE_TIME, 0) + ' мин.')

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--Вычисляемое поле "Количество услуг по ИППСУ".
--Складывается количество необходимых услуг по всем дням недели в месяце и отображается итоговая сумма.
ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN COUNT_ALL_CALCULATED;
ALTER TABLE dbo.CARE_DIARY_REPORT ADD COUNT_ALL_CALCULATED AS (
    DAY_1_ALL  + DAY_2_ALL  + DAY_3_ALL  + DAY_4_ALL  + DAY_5_ALL  + DAY_6_ALL  + DAY_7_ALL  + 
    DAY_8_ALL  + DAY_9_ALL  + DAY_10_ALL + DAY_11_ALL + DAY_12_ALL + DAY_13_ALL + DAY_14_ALL + 
    DAY_15_ALL + DAY_16_ALL + DAY_17_ALL + DAY_18_ALL + DAY_19_ALL + DAY_20_ALL + DAY_21_ALL + 
    DAY_22_ALL + DAY_23_ALL + DAY_24_ALL + DAY_25_ALL + DAY_26_ALL + DAY_27_ALL + DAY_28_ALL + 
    DAY_29_ALL + DAY_30_ALL + DAY_31_ALL 
);

--Вычисляемое поле "Количество исполненных услуг".
--Складывается количество оказанных услуг по всем дням недели в месяце и отображается итоговая сумма.
ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN COUNT_PERFORM_CALCULATED;
ALTER TABLE dbo.CARE_DIARY_REPORT ADD COUNT_PERFORM_CALCULATED AS (
    DAY_1_PERFORM  + DAY_2_PERFORM  + DAY_3_PERFORM  + DAY_4_PERFORM  + DAY_5_PERFORM  + DAY_6_PERFORM  + DAY_7_PERFORM  + 
    DAY_8_PERFORM  + DAY_9_PERFORM  + DAY_10_PERFORM + DAY_11_PERFORM + DAY_12_PERFORM + DAY_13_PERFORM + DAY_14_PERFORM + 
    DAY_15_PERFORM + DAY_16_PERFORM + DAY_17_PERFORM + DAY_18_PERFORM + DAY_19_PERFORM + DAY_20_PERFORM + DAY_21_PERFORM + 
    DAY_22_PERFORM + DAY_23_PERFORM + DAY_24_PERFORM + DAY_25_PERFORM + DAY_26_PERFORM + DAY_27_PERFORM + DAY_28_PERFORM + 
    DAY_29_PERFORM + DAY_30_PERFORM + DAY_31_PERFORM
);

--Вычисляемое поле заголовка количества необходимых и исполненных услуг.
--Складывается количество оказанных услуг и количество необходимых услуг по всем дням недели в месяце и отображается две итоговые суммы через дробь.
ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN COUNT_TITLE;
ALTER TABLE dbo.CARE_DIARY_REPORT ADD COUNT_TITLE AS (
    CONVERT(VARCHAR, 
        ISNULL(COUNT_PERFORM_INSERTED,
            DAY_1_PERFORM  + DAY_2_PERFORM  + DAY_3_PERFORM  + DAY_4_PERFORM  + DAY_5_PERFORM  + DAY_6_PERFORM  + DAY_7_PERFORM  + 
            DAY_8_PERFORM  + DAY_9_PERFORM  + DAY_10_PERFORM + DAY_11_PERFORM + DAY_12_PERFORM + DAY_13_PERFORM + DAY_14_PERFORM + 
            DAY_15_PERFORM + DAY_16_PERFORM + DAY_17_PERFORM + DAY_18_PERFORM + DAY_19_PERFORM + DAY_20_PERFORM + DAY_21_PERFORM + 
            DAY_22_PERFORM + DAY_23_PERFORM + DAY_24_PERFORM + DAY_25_PERFORM + DAY_26_PERFORM + DAY_27_PERFORM + DAY_28_PERFORM + 
            DAY_29_PERFORM + DAY_30_PERFORM + DAY_31_PERFORM
        )
    ) + 
    '/' + 
    CONVERT(VARCHAR, 
        ISNULL(COUNT_ALL_INSERTED,
            DAY_1_ALL  + DAY_2_ALL  + DAY_3_ALL  + DAY_4_ALL  + DAY_5_ALL  + DAY_6_ALL  + DAY_7_ALL  + 
            DAY_8_ALL  + DAY_9_ALL  + DAY_10_ALL + DAY_11_ALL + DAY_12_ALL + DAY_13_ALL + DAY_14_ALL + 
            DAY_15_ALL + DAY_16_ALL + DAY_17_ALL + DAY_18_ALL + DAY_19_ALL + DAY_20_ALL + DAY_21_ALL + 
            DAY_22_ALL + DAY_23_ALL + DAY_24_ALL + DAY_25_ALL + DAY_26_ALL + DAY_27_ALL + DAY_28_ALL + 
            DAY_29_ALL + DAY_30_ALL + DAY_31_ALL 
        )
    )
);

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--Вычисляемое поле "Время на оказание услуг по ИППСУ"
--Складывается количество необходимых услуг по всем дням недели в месяце и отображается произведение итоговой суммы на время оказания одной услуги по нормативу.
ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN TIME_ALL_CALCULATED
ALTER TABLE dbo.CARE_DIARY_REPORT ADD TIME_ALL_CALCULATED AS (
    EXECUTE_TIME * (
        DAY_1_ALL  + DAY_2_ALL  + DAY_3_ALL  + DAY_4_ALL  + DAY_5_ALL  + DAY_6_ALL  + DAY_7_ALL  + 
        DAY_8_ALL  + DAY_9_ALL  + DAY_10_ALL + DAY_11_ALL + DAY_12_ALL + DAY_13_ALL + DAY_14_ALL + 
        DAY_15_ALL + DAY_16_ALL + DAY_17_ALL + DAY_18_ALL + DAY_19_ALL + DAY_20_ALL + DAY_21_ALL + 
        DAY_22_ALL + DAY_23_ALL + DAY_24_ALL + DAY_25_ALL + DAY_26_ALL + DAY_27_ALL + DAY_28_ALL + 
        DAY_29_ALL + DAY_30_ALL + DAY_31_ALL 
    )
)

--Вычисляемое поле "Потраченное время на оказание услуг"
--Складывается количество оказанныъ услуг по всем дням недели в месяце и отображается произведение итоговой суммы на время оказания одной услуги по нормативу.
ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN TIME_PERFORM_CALCULATED
ALTER TABLE dbo.CARE_DIARY_REPORT ADD TIME_PERFORM_CALCULATED AS (
    EXECUTE_TIME * (
        DAY_1_PERFORM  + DAY_2_PERFORM  + DAY_3_PERFORM  + DAY_4_PERFORM  + DAY_5_PERFORM  + DAY_6_PERFORM  + DAY_7_PERFORM  + 
        DAY_8_PERFORM  + DAY_9_PERFORM  + DAY_10_PERFORM + DAY_11_PERFORM + DAY_12_PERFORM + DAY_13_PERFORM + DAY_14_PERFORM + 
        DAY_15_PERFORM + DAY_16_PERFORM + DAY_17_PERFORM + DAY_18_PERFORM + DAY_19_PERFORM + DAY_20_PERFORM + DAY_21_PERFORM + 
        DAY_22_PERFORM + DAY_23_PERFORM + DAY_24_PERFORM + DAY_25_PERFORM + DAY_26_PERFORM + DAY_27_PERFORM + DAY_28_PERFORM + 
        DAY_29_PERFORM + DAY_30_PERFORM + DAY_31_PERFORM
    )
)

--Вычисляемое поле заголовка количества необходимого времени и потраченного времени.
--Складывается количество оказанных услуг и количество необходимых услуг по всем дням недели в месяце и отображается две итоговых суммы через дробь, помноженные на время оказания одной услуги по нормативу.
ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN TIME_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD TIME_TITLE AS (
    dbo.fs_getTitleHourAndMinutes(
            ISNULL(TIME_PERFORM_INSERTED, EXECUTE_TIME * (
                    DAY_1_PERFORM  + DAY_2_PERFORM  + DAY_3_PERFORM  + DAY_4_PERFORM  + DAY_5_PERFORM  + DAY_6_PERFORM  + DAY_7_PERFORM  + 
                    DAY_8_PERFORM  + DAY_9_PERFORM  + DAY_10_PERFORM + DAY_11_PERFORM + DAY_12_PERFORM + DAY_13_PERFORM + DAY_14_PERFORM + 
                    DAY_15_PERFORM + DAY_16_PERFORM + DAY_17_PERFORM + DAY_18_PERFORM + DAY_19_PERFORM + DAY_20_PERFORM + DAY_21_PERFORM + 
                    DAY_22_PERFORM + DAY_23_PERFORM + DAY_24_PERFORM + DAY_25_PERFORM + DAY_26_PERFORM + DAY_27_PERFORM + DAY_28_PERFORM + 
                    DAY_29_PERFORM + DAY_30_PERFORM + DAY_31_PERFORM
                )
            ), 
        '{H}:{M}'
    ) + 
    '/' +
    dbo.fs_getTitleHourAndMinutes(
        ISNULL(TIME_ALL_INSERTED, EXECUTE_TIME * (
                DAY_1_ALL  + DAY_2_ALL  + DAY_3_ALL  + DAY_4_ALL  + DAY_5_ALL  + DAY_6_ALL  + DAY_7_ALL  + 
                DAY_8_ALL  + DAY_9_ALL  + DAY_10_ALL + DAY_11_ALL + DAY_12_ALL + DAY_13_ALL + DAY_14_ALL + 
                DAY_15_ALL + DAY_16_ALL + DAY_17_ALL + DAY_18_ALL + DAY_19_ALL + DAY_20_ALL + DAY_21_ALL + 
                DAY_22_ALL + DAY_23_ALL + DAY_24_ALL + DAY_25_ALL + DAY_26_ALL + DAY_27_ALL + DAY_28_ALL + 
                DAY_29_ALL + DAY_30_ALL + DAY_31_ALL 
            )
        ), 
        '{H}:{M}'
    )
)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--Заголовки для дней в итоговой таблице.
--Если тип строги 1 (Заголовок дней недели), то вычисляется день недели в соответствии с годом, месяцем и днем и выводится заголовок дня недели.
--Иначе выводится черезь дробь количество исполненных услуг и необходимое количество услуг. В случае, если данные числы равны, то выводится одно число, без дроби.
ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_1_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_1_TITLE AS (
    CASE 
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 1)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)
        WHEN DAY_1_PERFORM = 0 AND DAY_1_ALL = 0 THEN NULL 
        WHEN DAY_1_PERFORM = DAY_1_ALL THEN CONVERT(VARCHAR, DAY_1_ALL) 
        ELSE CONVERT(VARCHAR, DAY_1_PERFORM) + '/' + CONVERT(VARCHAR, DAY_1_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_2_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_2_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 2)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_2_PERFORM = 0 AND DAY_2_ALL = 0 THEN NULL 
        WHEN DAY_2_PERFORM = DAY_2_ALL THEN CONVERT(VARCHAR, DAY_2_ALL) 
        ELSE CONVERT(VARCHAR, DAY_2_PERFORM) + '/' + CONVERT(VARCHAR, DAY_2_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_3_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_3_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 3)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_3_PERFORM = 0 AND DAY_3_ALL = 0 THEN NULL 
        WHEN DAY_3_PERFORM = DAY_3_ALL THEN CONVERT(VARCHAR, DAY_3_ALL) 
        ELSE CONVERT(VARCHAR, DAY_3_PERFORM) + '/' + CONVERT(VARCHAR, DAY_3_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_4_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_4_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 4)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_4_PERFORM = 0 AND DAY_4_ALL = 0 THEN NULL 
        WHEN DAY_4_PERFORM = DAY_4_ALL THEN CONVERT(VARCHAR, DAY_4_ALL) 
        ELSE CONVERT(VARCHAR, DAY_4_PERFORM) + '/' + CONVERT(VARCHAR, DAY_4_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_5_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_5_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 5)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_5_PERFORM = 0 AND DAY_5_ALL = 0 THEN NULL 
        WHEN DAY_5_PERFORM = DAY_5_ALL THEN CONVERT(VARCHAR, DAY_5_ALL) 
        ELSE CONVERT(VARCHAR, DAY_5_PERFORM) + '/' + CONVERT(VARCHAR, DAY_5_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_6_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_6_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 6)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_6_PERFORM = 0 AND DAY_6_ALL = 0 THEN NULL 
        WHEN DAY_6_PERFORM = DAY_6_ALL THEN CONVERT(VARCHAR, DAY_6_ALL) 
        ELSE CONVERT(VARCHAR, DAY_6_PERFORM) + '/' + CONVERT(VARCHAR, DAY_6_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_7_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_7_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 7)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_7_PERFORM = 0 AND DAY_7_ALL = 0 THEN NULL 
        WHEN DAY_7_PERFORM = DAY_7_ALL THEN CONVERT(VARCHAR, DAY_7_ALL) 
        ELSE CONVERT(VARCHAR, DAY_7_PERFORM) + '/' + CONVERT(VARCHAR, DAY_7_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_8_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_8_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 8)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_8_PERFORM = 0 AND DAY_8_ALL = 0 THEN NULL 
        WHEN DAY_8_PERFORM = DAY_8_ALL THEN CONVERT(VARCHAR, DAY_8_ALL) 
        ELSE CONVERT(VARCHAR, DAY_8_PERFORM) + '/' + CONVERT(VARCHAR, DAY_8_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_9_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_9_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 9)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_9_PERFORM = 0 AND DAY_9_ALL = 0 THEN NULL 
        WHEN DAY_9_PERFORM = DAY_9_ALL THEN CONVERT(VARCHAR, DAY_9_ALL) 
        ELSE CONVERT(VARCHAR, DAY_9_PERFORM) + '/' + CONVERT(VARCHAR, DAY_9_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_10_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_10_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 10)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_10_PERFORM = 0 AND DAY_10_ALL = 0 THEN NULL 
        WHEN DAY_10_PERFORM = DAY_10_ALL THEN CONVERT(VARCHAR, DAY_10_ALL) 
        ELSE CONVERT(VARCHAR, DAY_10_PERFORM) + '/' + CONVERT(VARCHAR, DAY_10_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_11_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_11_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 11)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_11_PERFORM = 0 AND DAY_11_ALL = 0 THEN NULL 
        WHEN DAY_11_PERFORM = DAY_11_ALL THEN CONVERT(VARCHAR, DAY_11_ALL) 
        ELSE CONVERT(VARCHAR, DAY_11_PERFORM) + '/' + CONVERT(VARCHAR, DAY_11_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_12_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_12_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 12)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_12_PERFORM = 0 AND DAY_12_ALL = 0 THEN NULL 
        WHEN DAY_12_PERFORM = DAY_12_ALL THEN CONVERT(VARCHAR, DAY_12_ALL) 
        ELSE CONVERT(VARCHAR, DAY_12_PERFORM) + '/' + CONVERT(VARCHAR, DAY_12_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_13_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_13_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 13)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_13_PERFORM = 0 AND DAY_13_ALL = 0 THEN NULL 
        WHEN DAY_13_PERFORM = DAY_13_ALL THEN CONVERT(VARCHAR, DAY_13_ALL) 
        ELSE CONVERT(VARCHAR, DAY_13_PERFORM) + '/' + CONVERT(VARCHAR, DAY_13_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_14_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_14_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 14)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_14_PERFORM = 0 AND DAY_14_ALL = 0 THEN NULL 
        WHEN DAY_14_PERFORM = DAY_14_ALL THEN CONVERT(VARCHAR, DAY_14_ALL) 
        ELSE CONVERT(VARCHAR, DAY_14_PERFORM) + '/' + CONVERT(VARCHAR, DAY_14_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_15_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_15_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 15)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_15_PERFORM = 0 AND DAY_15_ALL = 0 THEN NULL 
        WHEN DAY_15_PERFORM = DAY_15_ALL THEN CONVERT(VARCHAR, DAY_15_ALL) 
        ELSE CONVERT(VARCHAR, DAY_15_PERFORM) + '/' + CONVERT(VARCHAR, DAY_15_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_16_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_16_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 16)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_16_PERFORM = 0 AND DAY_16_ALL = 0 THEN NULL 
        WHEN DAY_16_PERFORM = DAY_16_ALL THEN CONVERT(VARCHAR, DAY_16_ALL) 
        ELSE CONVERT(VARCHAR, DAY_16_PERFORM) + '/' + CONVERT(VARCHAR, DAY_16_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_17_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_17_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 17)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_17_PERFORM = 0 AND DAY_17_ALL = 0 THEN NULL 
        WHEN DAY_17_PERFORM = DAY_17_ALL THEN CONVERT(VARCHAR, DAY_17_ALL) 
        ELSE CONVERT(VARCHAR, DAY_17_PERFORM) + '/' + CONVERT(VARCHAR, DAY_17_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_18_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_18_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 18)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_18_PERFORM = 0 AND DAY_18_ALL = 0 THEN NULL 
        WHEN DAY_18_PERFORM = DAY_18_ALL THEN CONVERT(VARCHAR, DAY_18_ALL) 
        ELSE CONVERT(VARCHAR, DAY_18_PERFORM) + '/' + CONVERT(VARCHAR, DAY_18_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_19_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_19_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 19)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_19_PERFORM = 0 AND DAY_19_ALL = 0 THEN NULL 
        WHEN DAY_19_PERFORM = DAY_19_ALL THEN CONVERT(VARCHAR, DAY_19_ALL) 
        ELSE CONVERT(VARCHAR, DAY_19_PERFORM) + '/' + CONVERT(VARCHAR, DAY_19_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_20_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_20_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 20)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_20_PERFORM = 0 AND DAY_20_ALL = 0 THEN NULL 
        WHEN DAY_20_PERFORM = DAY_20_ALL THEN CONVERT(VARCHAR, DAY_20_ALL) 
        ELSE CONVERT(VARCHAR, DAY_20_PERFORM) + '/' + CONVERT(VARCHAR, DAY_20_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_21_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_21_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 21)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_21_PERFORM = 0 AND DAY_21_ALL = 0 THEN NULL 
        WHEN DAY_21_PERFORM = DAY_21_ALL THEN CONVERT(VARCHAR, DAY_21_ALL) 
        ELSE CONVERT(VARCHAR, DAY_21_PERFORM) + '/' + CONVERT(VARCHAR, DAY_21_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_22_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_22_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 22)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_22_PERFORM = 0 AND DAY_22_ALL = 0 THEN NULL 
        WHEN DAY_22_PERFORM = DAY_22_ALL THEN CONVERT(VARCHAR, DAY_22_ALL) 
        ELSE CONVERT(VARCHAR, DAY_22_PERFORM) + '/' + CONVERT(VARCHAR, DAY_22_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_23_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_23_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 23)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_23_PERFORM = 0 AND DAY_23_ALL = 0 THEN NULL 
        WHEN DAY_23_PERFORM = DAY_23_ALL THEN CONVERT(VARCHAR, DAY_23_ALL) 
        ELSE CONVERT(VARCHAR, DAY_23_PERFORM) + '/' + CONVERT(VARCHAR, DAY_23_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_24_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_24_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 24)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_24_PERFORM = 0 AND DAY_24_ALL = 0 THEN NULL 
        WHEN DAY_24_PERFORM = DAY_24_ALL THEN CONVERT(VARCHAR, DAY_24_ALL) 
        ELSE CONVERT(VARCHAR, DAY_24_PERFORM) + '/' + CONVERT(VARCHAR, DAY_24_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_25_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_25_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 25)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_25_PERFORM = 0 AND DAY_25_ALL = 0 THEN NULL 
        WHEN DAY_25_PERFORM = DAY_25_ALL THEN CONVERT(VARCHAR, DAY_25_ALL) 
        ELSE CONVERT(VARCHAR, DAY_25_PERFORM) + '/' + CONVERT(VARCHAR, DAY_25_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_26_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_26_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 26)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_26_PERFORM = 0 AND DAY_26_ALL = 0 THEN NULL 
        WHEN DAY_26_PERFORM = DAY_26_ALL THEN CONVERT(VARCHAR, DAY_26_ALL) 
        ELSE CONVERT(VARCHAR, DAY_26_PERFORM) + '/' + CONVERT(VARCHAR, DAY_26_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_27_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_27_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 27)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_27_PERFORM = 0 AND DAY_27_ALL = 0 THEN NULL 
        WHEN DAY_27_PERFORM = DAY_27_ALL THEN CONVERT(VARCHAR, DAY_27_ALL) 
        ELSE CONVERT(VARCHAR, DAY_27_PERFORM) + '/' + CONVERT(VARCHAR, DAY_27_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_28_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_28_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 28)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) 
        WHEN DAY_28_PERFORM = 0 AND DAY_28_ALL = 0 THEN NULL 
        WHEN DAY_28_PERFORM = DAY_28_ALL THEN CONVERT(VARCHAR, DAY_28_ALL) 
        ELSE CONVERT(VARCHAR, DAY_28_PERFORM) + '/' + CONVERT(VARCHAR, DAY_28_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_29_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_29_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN CASE 
            WHEN DAY(dbo.fs_getLastDayOfMonth(YEAR, MONTH)) >= 29 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 29)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)  
            ELSE '-' 
        END
        WHEN DAY_29_PERFORM = 0 AND DAY_29_ALL = 0 THEN NULL 
        WHEN DAY_29_PERFORM = DAY_29_ALL THEN CONVERT(VARCHAR, DAY_29_ALL) 
        ELSE CONVERT(VARCHAR, DAY_29_PERFORM) + '/' + CONVERT(VARCHAR, DAY_29_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_30_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_30_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN CASE 
            WHEN DAY(dbo.fs_getLastDayOfMonth(YEAR, MONTH)) >= 30 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 30)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)  
            ELSE '-' 
        END
        WHEN DAY_30_PERFORM = 0 AND DAY_30_ALL = 0 THEN NULL 
        WHEN DAY_30_PERFORM = DAY_30_ALL THEN CONVERT(VARCHAR, DAY_30_ALL) 
        ELSE CONVERT(VARCHAR, DAY_30_PERFORM) + '/' + CONVERT(VARCHAR, DAY_30_ALL) 
    END
)

ALTER TABLE dbo.CARE_DIARY_REPORT DROP COLUMN DAY_31_TITLE
ALTER TABLE dbo.CARE_DIARY_REPORT ADD DAY_31_TITLE AS (
    CASE
        WHEN ROW_TYPE = 1 THEN CASE 
            WHEN DAY(dbo.fs_getLastDayOfMonth(YEAR, MONTH)) = 31 THEN dbo.fs_getTitleDayOfWeek(DATEPART(DW, dbo.fs_getDate(YEAR, MONTH, 31)), DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)  
            ELSE '-' 
        END
        WHEN DAY_31_PERFORM = 0 AND DAY_31_ALL = 0 THEN NULL 
        WHEN DAY_31_PERFORM = DAY_31_ALL THEN CONVERT(VARCHAR, DAY_31_ALL) 
        ELSE CONVERT(VARCHAR, DAY_31_PERFORM) + '/' + CONVERT(VARCHAR, DAY_31_ALL) 
    END
)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------